name: Build Resume

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Overleaf project
        run: |
          git clone https://$OVERLEAF_EMAIL:$OVERLEAF_TOKEN@git.overleaf.com/69b65297c9c8842b2d6ed896 project

      - name: Install LaTeX
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-base texlive-latex-extra

      - name: Compile
        run: |
          cd project
          pdflatex main.tex

      - name: Copy PDF
        run: |
          cp project/main.pdf resume.pdf

      - name: Commit PDF
        run: |
          git init
          git config --global user.name github-actions
          git config --global user.email actions@github.com
          git add resume.pdf
          git commit -m "update resume" || echo "no changes"
          git push
